### ISSUE TITLE
No improvement after training

### ISSUE THREAD

**Issue by andreydung** [lvdmaaten/metriclearning#1]
I used LMNN on my own dataset (size 300x258), and the objective function keep going up:

Training nearest neighbor error before LMNN: 0.17834394904459
Test nearest neighbor error before LMNN: 0.20253164556962
Iteration 1: loss function is 3615689.8427856 and number of constraint violations is 1236
Iteration 10: loss function is 1.8267519858809e+15 and number of constraint violations is 1343
Iteration 20: loss function is 1.8230889226207e+15 and number of constraint violations is 1343
Iteration 30: loss function is 1.8190426219014e+15 and number of constraint violations is 1343
Iteration 40: loss function is 1.814572988601e+15 and number of constraint violations is 1343
Iteration 50: loss function is 1.8096357327652e+15 and number of constraint violations is 1343
Performed LMNN in 2.8080189228058 seconds.
Training nearest neighbor error after LMNN: 0.17834394904459
Test nearest neighbor error after LMNN: 0.20253164556962

What would be the reason for this? Do I need to find a better starting point, or is there something wrong with data?

Thanks.

**Comment by lvdmaaten** [comment]
Is the LMNN demo working fine for you, and producing something like this?

```
user$ th demos/demo_lmnn.lua 
Training nearest neighbor error before LMNN: 0.11   
Test nearest neighbor error before LMNN: 0.155  
Iteration 1: loss function is 50.483752119061 and number of constraint violations is 6092   
Iteration 10: loss function is 11.473349473716 and number of constraint violations is 3711  
Iteration 20: loss function is 8.4168106341386 and number of constraint violations is 3297  
Iteration 30: loss function is 6.3856314622743 and number of constraint violations is 4232  
Iteration 40: loss function is 5.496927126009 and number of constraint violations is 5227   
Iteration 50: loss function is 5.1084075760069 and number of constraint violations is 5861  
Performed LMNN in 29.303303003311 seconds.  
Training nearest neighbor error after LMNN: 0.047   
Test nearest neighbor error after LMNN: 0.139
```

Can you send me a copy of your data set so I can try and reproduce the problem?

**Comment by andreydung** [comment]
This is the dataset and code to reproduce the problem

https://www.dropbox.com/s/mx0l3kf0myt0qpn/Dzung.zip?dl=0

Thanks!

**Comment by lvdmaaten** [comment]
This appears to be a numerical problem. Please normalize the data before feeding it to LMNN:

``` lua
-- normalize data:
local min_X = torch.min(train_X)
train_X:add(-min_X)
 test_X:add(-min_X)
local max_X = torch.max(train_X)
train_X:mul(1 / max_X)
 test_X:mul(1 / max_X)
```

After this, there is still no improvement in terms of classification error, but at least the LMNN loss is going down:

```
Training nearest neighbor error before LMNN: 0.17834394904459   
Test nearest neighbor error before LMNN: 0.20253164556962   
Iteration 1: loss function is 220.63997238699 and number of constraint violations is 147168 
Iteration 10: loss function is 177.70233116931 and number of constraint violations is 130863    
Iteration 20: loss function is 161.56062650219 and number of constraint violations is 125203    
Iteration 30: loss function is 149.93514621984 and number of constraint violations is 120748    
Iteration 40: loss function is 141.05243137679 and number of constraint violations is 116402    
Iteration 50: loss function is 133.61898088096 and number of constraint violations is 112697    
Performed LMNN in 4.8568370342255 seconds.  
Training nearest neighbor error after LMNN: 0.20700636942675    
Test nearest neighbor error after LMNN: 0.20253164556962
```

You may want to run for more iterations to see if that improved your results.
