### ISSUE TITLE
Error with sample code

### ISSUE THREAD

**Issue by sourabhd** [lvdmaaten/metriclearning#2]
I see the following error on running example code from readme.
I installed using 'luarocks install metriclearning'

Error:

th test_metriclearning.lua 
/home/sourabh.d/installs/torch/install/bin/luajit: ...alls/torch/install/share/lua/5.1/metriclearning/lmnn.lua:42: bad argument #1 to 'map' (torch.DoubleTensor expected, got torch.ByteTensor)
stack traceback:
        [C]: in function 'error'
        ...abh.d/installs/torch/install/share/lua/5.1/torch/FFI.lua:6: in function 'checkArgument'
        ...abh.d/installs/torch/install/share/lua/5.1/torch/FFI.lua:13: in function 'checkArgumentType'
        ...abh.d/installs/torch/install/share/lua/5.1/torch/FFI.lua:134: in function 'map'
        ...alls/torch/install/share/lua/5.1/metriclearning/lmnn.lua:42: in function 'lmnn'
        test_metriclearning.lua:10: in main chunk
        [C]: in function 'dofile'
        ...alls/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by lvdmaaten** [comment]
Fixed by https://github.com/lvdmaaten/metriclearning/commit/6d429b8b409d19de2f9c49da0130db35920720a7
